### ISSUE TITLE
PID Tuning Parameters

### ISSUE THREAD

**Issue by Elektron97** [BRAIR-Education/dapozzo_line_tracking#2]
Be careful on the current values of the PID gains. Maybe you chose these params just for prototyping your code, but usually is very unlikely that $k_p = k_i = k_d = 0.01$ works. *Remember to tune your PID*. 

Suggestion: To tune your PID, can be useful to use [plotjuggler](https://plotjuggler.io/).

**Comment by Nargaruga** [comment]
Yes, those values are temporary and were picked just to quickly test the code. I will look into tuning the PID with more sensible gains. Thanks for the link!

**Comment by Nargaruga** [comment]
![0,05-0,015-0,01](https://github.com/BRAIR-Education/dapozzo_line_tracking/assets/43698284/1526e19b-f481-49e0-85ed-a62dab727ad5)

The provided plot shows the evolution of the error over a 30s run with the following PID parameters:
- P: 0.05
- I: 0.015
- D: 0.01

There is a big overshoot at the beginning, probably caused by the fact that the car starts off-center. I tried to increase a bit the I and D terms but it appears that even very small increases cause the car to completely lose control right away. At this point I don't know if it's a problem with my PID implementation, the Camera node or what.

**Comment by Elektron97** [comment]
I try your nodes and I find out that the car goes out of track when **the curvature of the track increases very rapidly**. This because the yellow track goes out from the field of view of your camera. After looking your error plot and the simulation, maybe you can also try to record some bags file with some simulations and understand the critical point in which your algorithm fail.
If you are more confident, you can analyze the bag files in [MATLAB](https://it.mathworks.com/help/ros/ref/readmessages.html), or still using PlotJuggler.

This visualization task can be useful also for your final presentation for the exam.
